# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d3a7d2716c4e10d905d898e564318dd466bd33db86292a0c7fb7277b67a43fa4ec0320ed59c1a9a9dd967e69723caaf16e85459928b6b291daa337e92486d57e

test:
  secret_key_base: 0528b26167deda2e9fa8561f6a33cc063b099de8dbd978287cb052536d0843ca6935a9023b431131b8cfbd657b42bc26353a64d2458933abe94ace14b977486f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
